/**
 * Mock data that mirrors the expected backend FinalReport schema.
 * Used for frontend development before backend integration.
 */
const mockReport = {
  repository: {
    name: 'react',
    owner: 'facebook',
    full_name: 'facebook/react',
    description: 'The library for web and native user interfaces.',
    url: 'https://github.com/facebook/react',
    stars: 224500,
    forks: 45800,
    open_issues: 980,
    watchers: 6700,
    default_branch: 'main',
    created_at: '2013-05-24T16:15:54Z',
    updated_at: '2024-12-20T08:30:00Z',
    languages: {
      JavaScript: 58,
      TypeScript: 28,
      CSS: 6,
      HTML: 4,
      'C++': 2,
      Python: 2,
    },
    total_commits: 17240,
    total_contributors: 42,
  },

  ai_summary: {
    project_explanation:
      "React is a widely-used open-source JavaScript library maintained by Meta (Facebook). It lets developers build interactive user interfaces by breaking them into small, reusable pieces called 'components'. Think of it like building with LEGO blocks — each block handles one part of a webpage, and you can combine them to build complex applications. React uses a clever system called the 'Virtual DOM' to update only the parts of a page that actually change, making apps faster and smoother.",
    team_behavior:
      'The React team shows a mature, well-organized development pattern. Core maintainers like Dan Abramov and Andrew Clark consistently drive architecture decisions and large features. The team operates on a regular release cadence with clear communication through RFCs. There are distinct roles — some contributors focus on core runtime, others on developer tools, and a growing set on the new React Server Components infrastructure.',
    overall_health: 'excellent',
  },

  contributors: [
    {
      username: 'gaearon',
      avatar_url: 'https://avatars.githubusercontent.com/u/810438',
      commits: 1543,
      lines_added: 89400,
      lines_removed: 52100,
      commit_quality_score: 94,
      personality: 'architect',
      ai_code_likelihood: 5,
      risk_level: 'low',
      contribution_pattern: 'consistent',
      first_commit: '2015-07-03T10:00:00Z',
      last_commit: '2024-12-15T14:30:00Z',
      active_days: 1820,
      avg_commits_per_week: 4.2,
      top_files: ['packages/react-dom/src/', 'packages/react/', 'packages/shared/'],
      strengths: ['Exceptional commit quality', 'Core architecture leadership', 'Excellent documentation'],
      concerns: [],
    },
    {
      username: 'acdlite',
      avatar_url: 'https://avatars.githubusercontent.com/u/3624098',
      commits: 1205,
      lines_added: 67200,
      lines_removed: 41300,
      commit_quality_score: 91,
      personality: 'workhorse',
      ai_code_likelihood: 3,
      risk_level: 'low',
      contribution_pattern: 'consistent',
      first_commit: '2016-01-12T09:00:00Z',
      last_commit: '2024-12-18T11:00:00Z',
      active_days: 1650,
      avg_commits_per_week: 3.8,
      top_files: ['packages/react-reconciler/', 'packages/react-server/', 'packages/scheduler/'],
      strengths: ['Reliable feature delivery', 'Deep reconciler expertise', 'Strong testing discipline'],
      concerns: [],
    },
    {
      username: 'sebmarkbage',
      avatar_url: 'https://avatars.githubusercontent.com/u/63648',
      commits: 980,
      lines_added: 54300,
      lines_removed: 38700,
      commit_quality_score: 96,
      personality: 'perfectionist',
      ai_code_likelihood: 2,
      risk_level: 'low',
      contribution_pattern: 'consistent',
      first_commit: '2013-06-01T08:00:00Z',
      last_commit: '2024-11-20T16:00:00Z',
      active_days: 2100,
      avg_commits_per_week: 2.5,
      top_files: ['packages/react-server/', 'packages/react-client/', 'packages/shared/'],
      strengths: ['Highest code quality scores', 'Pioneered Server Components', 'Clean architecture'],
      concerns: [],
    },
    {
      username: 'sophiebits',
      avatar_url: 'https://avatars.githubusercontent.com/u/6820',
      commits: 720,
      lines_added: 38900,
      lines_removed: 22600,
      commit_quality_score: 88,
      personality: 'mentor',
      ai_code_likelihood: 4,
      risk_level: 'low',
      contribution_pattern: 'consistent',
      first_commit: '2013-08-15T12:00:00Z',
      last_commit: '2024-10-05T09:00:00Z',
      active_days: 1500,
      avg_commits_per_week: 2.1,
      top_files: ['packages/react-dom/', 'packages/react-dom/src/events/', 'fixtures/'],
      strengths: ['Strong mentoring presence', 'DOM & events expertise', 'Cross-team collaboration'],
      concerns: ['Reduced activity in recent months'],
    },
    {
      username: 'rickhanlonii',
      avatar_url: 'https://avatars.githubusercontent.com/u/2440089',
      commits: 340,
      lines_added: 18200,
      lines_removed: 9800,
      commit_quality_score: 72,
      personality: 'explorer',
      ai_code_likelihood: 12,
      risk_level: 'medium',
      contribution_pattern: 'sporadic',
      first_commit: '2020-03-10T14:00:00Z',
      last_commit: '2024-12-01T10:00:00Z',
      active_days: 420,
      avg_commits_per_week: 1.2,
      top_files: ['packages/react-devtools/', 'packages/react-debug-tools/', 'scripts/'],
      strengths: ['DevTools expertise', 'Wide codebase familiarity'],
      concerns: ['Inconsistent commit patterns', 'Higher AI-assisted code likelihood'],
    },
    {
      username: 'new-contributor-42',
      avatar_url: '',
      commits: 28,
      lines_added: 1200,
      lines_removed: 400,
      commit_quality_score: 45,
      personality: 'newcomer',
      ai_code_likelihood: 35,
      risk_level: 'high',
      contribution_pattern: 'burst',
      first_commit: '2024-11-01T10:00:00Z',
      last_commit: '2024-11-15T16:00:00Z',
      active_days: 14,
      avg_commits_per_week: 14,
      top_files: ['docs/', 'packages/react/README.md'],
      strengths: ['Enthusiastic new contributor'],
      concerns: ['Very short history', 'Low commit quality', 'High AI-code estimate', 'Burst pattern suggests rushed work'],
    },
  ],

  insights: {
    strengths: [
      'Exceptionally well-maintained project with strong core maintainer team',
      'High commit message quality across senior contributors (avg 90+)',
      'Clear separation of concerns in the codebase architecture',
      'Regular release cadence with excellent documentation',
      'Diverse contributor base with clear expertise areas',
    ],
    weaknesses: [
      'Knowledge concentration — top 3 contributors account for 60% of commits',
      'Some areas of the codebase have single-point-of-failure contributors',
      'Newer contributors show lower commit quality and may need mentoring',
      'Test coverage varies significantly across packages',
    ],
    risks: [
      'Bus factor risk: Server Components knowledge concentrated in 1-2 people',
      'New contributor "new-contributor-42" shows high AI-code markers and low quality — needs review',
      'Declining activity from some long-term contributors may indicate burnout',
    ],
  },

  recommendations: [
    {
      type: 'positive',
      target: 'gaearon',
      title: 'Continue Leadership Role',
      detail: 'Dan Abramov consistently delivers high-quality, well-documented contributions. His architectural vision is key to the project\'s direction. Recommend maintaining his core maintainer role.',
    },
    {
      type: 'positive',
      target: 'sebmarkbage',
      title: 'Knowledge Sharing Priority',
      detail: 'Sebastian has the highest code quality but concentrated knowledge in Server Components. Recommend pairing sessions to spread this expertise to reduce bus factor risk.',
    },
    {
      type: 'warning',
      target: 'rickhanlonii',
      title: 'Establish Consistent Cadence',
      detail: 'Shows sporadic contribution patterns. Consider establishing a regular contribution schedule or assigning focused project areas to improve consistency.',
    },
    {
      type: 'critical',
      target: 'new-contributor-42',
      title: 'Review Contributions Carefully',
      detail: 'High AI-generated code markers (35%), low commit quality (45/100), and a burst contribution pattern. All contributions should undergo thorough code review before merging.',
    },
    {
      type: 'general',
      target: 'team',
      title: 'Reduce Knowledge Silos',
      detail: 'Implement a rotation program where contributors periodically work outside their specialty areas. This reduces bus-factor risk and improves overall team resilience.',
    },
  ],

  patterns: {
    hourly_distribution: [2, 1, 0, 0, 1, 2, 5, 12, 18, 22, 25, 20, 15, 18, 24, 22, 19, 14, 10, 8, 6, 4, 3, 2],
    daily_distribution: [5, 22, 25, 24, 23, 20, 8],
    commit_frequency: {
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      data: [142, 165, 178, 155, 190, 170, 120, 145, 180, 195, 160, 130],
    },
  },

  generated_at: new Date().toISOString(),
};

export default mockReport;
