from pydantic import BaseModel
from typing import List, Optional


class LLMRecommendation(BaseModel):
    """A single actionable recommendation from the LLM."""
    type: str   # 'positive', 'warning', 'critical', 'general'
    target: str  # contributor username or 'team'
    title: str
    detail: str


class LLMInsights(BaseModel):
    """Structured insights generated by the local LLM (Ollama)."""
    project_explanation: str
    team_behavior: str
    overall_health: str   # 'excellent', 'good', 'fair', 'poor'
    strengths: List[str]
    weaknesses: List[str]
    risks: List[str]
    recommendations: List[LLMRecommendation]
    llm_available: bool = True
    model_used: Optional[str] = None
